"""项目提示词统一入口。

按域拆分模块：
- ``prompts.agent`` — Agent / 工具路由
- ``prompts.memory`` — 记忆与语义图
- ``prompts.rag`` — RAG 生成

渲染占位符请使用 :func:`prompts.render_prompt`。
"""

from .agent import (
    DEFAULT_REACT_SYSTEM_PROMPT,
    DEFAULT_SIMPLE_AGENT_SYSTEM_PROMPT,
    PLAN_AND_SOLVE_PLANNER_PROMPT,
    PLAN_AND_SOLVE_SOLVER_PROMPT,
    PLAN_AND_SOLVE_SYNTHESIS_PROMPT,
    REACT_USER_PROMPT_TEMPLATE,
    REFLECTION_CODE_SYSTEM_PROMPT,
    REFLECTION_CRITIQUE_PROMPT,
    REFLECTION_INITIAL_SYSTEM_PROMPT,
    REFLECTION_NO_CHANGES_MARKER,
    REFLECTION_REVISE_PROMPT,
    SEARCH_ROUTING_PROMPT,
)
from .memory import (
    CONCEPT_EXTRACTION_SYSTEM_PROMPT,
    CONCEPT_EXTRACTION_USER_PROMPT_TEMPLATE,
    build_concept_extraction_messages,
)
from .rag import (
    RAG_ANSWER_SYSTEM_PROMPT,
    RAG_ANSWER_USER_PROMPT_TEMPLATE,
)
from .render import render_prompt

__all__ = [
    "DEFAULT_REACT_SYSTEM_PROMPT",
    "DEFAULT_SIMPLE_AGENT_SYSTEM_PROMPT",
    "PLAN_AND_SOLVE_PLANNER_PROMPT",
    "PLAN_AND_SOLVE_SOLVER_PROMPT",
    "PLAN_AND_SOLVE_SYNTHESIS_PROMPT",
    "REACT_USER_PROMPT_TEMPLATE",
    "REFLECTION_CODE_SYSTEM_PROMPT",
    "REFLECTION_CRITIQUE_PROMPT",
    "REFLECTION_INITIAL_SYSTEM_PROMPT",
    "REFLECTION_NO_CHANGES_MARKER",
    "REFLECTION_REVISE_PROMPT",
    "SEARCH_ROUTING_PROMPT",
    "CONCEPT_EXTRACTION_SYSTEM_PROMPT",
    "CONCEPT_EXTRACTION_USER_PROMPT_TEMPLATE",
    "build_concept_extraction_messages",
    "RAG_ANSWER_SYSTEM_PROMPT",
    "RAG_ANSWER_USER_PROMPT_TEMPLATE",
    "render_prompt",
]
